Loading multiple GPT2 checkpoints on same computer. (#540)
* GPT2 initializer tries to load parameters by directly referencing `Transformer` directory under temporary directory, which happens to be where CheckpointReader keeps those files if modelName is `Transformer`. This works if there is only one checkpoint on the system, for example 117M. Using GPT2 with other checkpoints will break with shape errors.
```
Fatal error: Input to reshape is a tensor with 5120 values, but the requested shape has 5100: file /Users/swiftninjas/s4tf/tensorflow-swift-apis/Sources/TensorFlow/Bindings/EagerExecution.swift, line 301
```
This change uses the directory name as part of the modelName parameter of CheckpointReader, for example: GPT2-117M, GPT2-345M to avoid mixing files. It also uses CheckpointReader's localCheckpointLocation to get the directory of the locally stored checkpoint files.

* Remove `FileManager` access since it is not needed here.